# Generated by Django 5.2.4 on 2025-09-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WearUpBack', '0002_product_caption_product_comments_product_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='WearUpBack.size'),
        ),
    ]
