# Generated by Django 5.2.4 on 2025-09-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WearUpBack', '0004_remove_product_sizes_delete_size_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
