# Generated by Django 5.2.4 on 2025-09-27 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WearUpBack', '0005_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shares',
        ),
        migrations.RemoveField(
            model_name='product',
            name='timeAgo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
