# Generated by Django 5.2.4 on 2025-09-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WearUpBack', '0010_color_coupon_rename_rating_product_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='alternate_email',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
