# Generated by Django 5.2.4 on 2025-09-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WearUpBack', '0011_remove_userprofile_alternate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
