# Generated by Django 5.2.4 on 2025-09-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WearUpBack', '0012_userprofile_alternate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='WearUpBack.size'),
        ),
    ]
