# Generated by Django 5.2.4 on 2025-09-29 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WearUpBack', '0013_remove_size_category_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='category',
        ),
    ]
