# Generated by Django 5.2.4 on 2025-09-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WearUpBack', '0014_remove_size_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
