# Generated by Django 5.2.4 on 2025-09-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WearUpBack', '0015_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
