# Generated by Django 5.2.4 on 2025-09-29 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WearUpBack', '0016_delete_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
